'use client';

import { useEffect, useState } from 'react';
import AppShell from '@/components/layout/AppShell';
import { api } from '@/lib/api';

export default function IntelReportsPage() {
  const [brief, setBrief] = useState<any>(null);
  const [refreshing, setRefreshing] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.getDailyBrief().then(b => { setBrief(b); setLoading(false); }).catch(() => setLoading(false));
  }, []);

  const handleRefresh = async () => {
    setRefreshing(true);
    try {
      const res = await fetch('https://bahamut-production.up.railway.app/api/v1/reports/daily-brief/refresh', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('bahamut_token')}`,
        },
      });
      const b = await res.json();
      setBrief(b);
    } catch (e) { console.error(e); }
    setRefreshing(false);
  };

  const sections = [
    { key: 'overview', title: 'Market Overview', icon: '◉' },
    { key: 'key_movers', title: 'Key Movers', icon: '⚡' },
    { key: 'signal_summary', title: 'AI Signal Summary', icon: '◎' },
    { key: 'risk_events', title: 'Risk Events', icon: '◆' },
    { key: 'outlook', title: 'Trading Outlook', icon: '▤' },
  ];

  return (
    <AppShell>
      <div className="space-y-5">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">Intel Reports</h1>
            <p className="text-sm text-text-secondary mt-1">AI-generated daily market intelligence brief</p>
          </div>
          <button onClick={handleRefresh} disabled={refreshing}
            className="bg-accent-violet hover:bg-accent-violet/90 text-white font-semibold px-4 py-1.5 rounded-md text-sm disabled:opacity-50">
            {refreshing ? 'Generating...' : 'Regenerate Brief'}
          </button>
        </div>

        {loading ? (
          <div className="bg-bg-secondary border border-border-default rounded-lg p-8 text-center text-text-muted">Loading brief...</div>
        ) : brief ? (
          <>
            {/* Header card */}
            <div className="bg-bg-secondary border border-border-default rounded-lg p-5">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <div className="text-lg font-bold">Daily Market Brief</div>
                  <div className="text-xs text-text-muted mt-0.5">
                    {brief.date} · Generated by {brief.model || 'AI'} · {brief.signals_analyzed || 0} signals analyzed · {brief.news_analyzed || 0} news articles
                  </div>
                </div>
                <span className={`px-3 py-1 rounded-full text-xs font-semibold ${
                  brief.regime === 'RISK_ON' ? 'bg-accent-emerald/20 text-accent-emerald border border-accent-emerald/30' :
                  brief.regime === 'RISK_OFF' ? 'bg-accent-crimson/20 text-accent-crimson border border-accent-crimson/30' :
                  'bg-accent-amber/20 text-accent-amber border border-accent-amber/30'
                }`}>
                  {brief.regime || 'MIXED'}
                </span>
              </div>

              {/* Sections */}
              <div className="space-y-4">
                {sections.map(section => {
                  const content = brief[section.key];
                  if (!content) return null;
                  return (
                    <div key={section.key} className="border-l-2 border-accent-violet pl-4">
                      <div className="text-xs text-accent-violet font-semibold uppercase tracking-wider mb-1 flex items-center gap-2">
                        <span>{section.icon}</span> {section.title}
                      </div>
                      <p className="text-sm text-text-primary leading-relaxed">{content}</p>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-3 gap-4">
              <div className="bg-bg-secondary border border-border-default rounded-lg p-4 text-center">
                <div className="text-2xl font-mono font-semibold text-accent-violet">{brief.signals_analyzed || 0}</div>
                <div className="text-xs text-text-muted">Signals Analyzed</div>
              </div>
              <div className="bg-bg-secondary border border-border-default rounded-lg p-4 text-center">
                <div className="text-2xl font-mono font-semibold text-accent-emerald">{brief.news_analyzed || 0}</div>
                <div className="text-xs text-text-muted">News Articles</div>
              </div>
              <div className="bg-bg-secondary border border-border-default rounded-lg p-4 text-center">
                <div className="text-2xl font-mono font-semibold text-accent-amber">{brief.events_upcoming || 0}</div>
                <div className="text-xs text-text-muted">High Impact Events</div>
              </div>
            </div>
          </>
        ) : (
          <div className="bg-bg-secondary border border-border-default rounded-lg p-8 text-center">
            <div className="text-text-muted">No brief generated yet. Click Regenerate to create one.</div>
          </div>
        )}
      </div>
    </AppShell>
  );
}
